function [fitresult, gof] = TTO_data_fit(throtle, Mom, Omega)
%CREATEFIT(THROTLE,MOM,OMEGA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : throtle
%      Y Input : Mom
%      Z Output: Omega
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2014 18:25:10


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( throtle, Mom, Omega );

% Set up fittype and options.
ft = fittype( '(a*log((x)*atan2(x,y))+b)/(y+c)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.0781755287531837 0.442678269775446 0.106652770180584];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'Omega vs. throtle, Mom', 'Location', 'NorthEast' );
% Label axes
xlabel( 'throtle' );
ylabel( 'Mom' );
zlabel( 'Omega' );
grid on
view( -48.5, 20 );


