function [fitresult, gof] = TTO_cubic(throtle, Mom, Omega)
%CREATEFIT(THROTLE,MOM,OMEGA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : throtle
%      Y Input : Mom
%      Z Output: Omega
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Dec-2014 19:22:45


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( throtle, Mom, Omega );

% Set up fittype and options.
ft = 'cubicinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
h = plot( fitresult, [xData, yData], zData );

legend( h, 'untitled fit 1', 'Omega vs. throtle, Mom', 'Location', 'NorthEast' );
% Label axes
xlabel( 'throtle' );
ylabel( 'Mom' );
zlabel( 'Omega' );
grid on
view( -64.5, -6 );


