function [fitresult, gof] = DosDEta_V(VV, etaa)
%CREATEFIT(VV,ETAA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : VV
%      Y Output: etaa
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2015 17:02:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( VV, etaa );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.StartPoint = [-0.293452210821191 1.42953522939573 0.925771530944304 0.233652833155464];
opts.Upper = [Inf Inf Inf Inf];
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'etaa vs. VV', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'VV' );
ylabel( 'etaa' );
grid on


