function [fitresult, gof] = Fit_eta_expand(RPS, V_etaexpand, etaexpand)
%CREATEFIT(RPS,V_ETAEXPAND,ETAEXPAND)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : RPS
%      Y Input : V_etaexpand
%      Z Output: etaexpand
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2015 18:52:34


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( RPS, V_etaexpand, etaexpand );

% Set up fittype and options.
ft = fittype( 'a*x^d*y^b+c', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.StartPoint = [0.171048017525447 0.938557864331842 0.590483177142572 0.44063468076084];
opts.Upper = [Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'etaexpand vs. RPS, V_etaexpand', 'Location', 'NorthEast' );
% Label axes
xlabel( 'RPS' );
ylabel( 'V_etaexpand' );
zlabel( 'etaexpand' );
grid on
view( -22.5, 20 );


