function [fitresult, gof] = Fit_eta_C_P(V, C_P, eta)
%CREATEFIT(V,C_P,ETA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Input : C_P
%      Z Output: eta
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Feb-2015 18:37:23


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( V, C_P, eta );

% Set up fittype and options.
ft = fittype( 'poly22' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'eta vs. V, C_P', 'Location', 'NorthEast' );
% Label axes
xlabel( 'V' );
ylabel( 'C_P' );
zlabel( 'eta' );
grid on
view( -12.5, 70 );


